http request "curl "http://localhost:25025/updatecustomer/1" 
-X "OPTIONS" 
-H "Accept: /" 
-H "Accept-Language: en-CA,en;q=0.9,ru-RU;q=0.8,ru;q=0.7,en-GB;q=0.6,en-US;q=0.5" 
-H "Access-Control-Request-Headers: content-type" 
-H "Access-Control-Request-Method: PUT" 
-H "Connection: keep-alive" 
-H "Origin: null" 
-H "Sec-Fetch-Dest: empty" 
-H "Sec-Fetch-Mode: cors" 
-H "Sec-Fetch-Site: cross-site" 
-H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" 